language: swift
os: osx
osx_image: xcode14.2

before_install:
  - gem install xcpretty

before_script:
  - open -a Simulator

script:
  - echo "Starting build process..."
  - travis_wait 40 set -o pipefail && xcodebuild -project ToDoListAppTravis.xcodeproj -scheme ToDoListAppTravis -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' build | xcpretty
  - echo "Build completed, starting tests..."
  - echo "Running tests..."
  - travis_wait 40 set -o pipefail && xcodebuild -project ToDoListAppTravis.xcodeproj -scheme ToDoListAppTravis -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test | xcpretty
  - echo "Tests completed."
