language: swift
os: osx
osx_image: xcode14.2

before_install:
  - gem install xcpretty

script:
  - echo "Starting build process..."
  - travis_wait 30 set -o pipefail && xcodebuild -project ToDoListAppTravis.xcodeproj -scheme ToDoListAppTravis -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' build | xcpretty --reporter json-compilation-database --output build_output.json
  - echo "Build completed, starting tests..."
  - travis_wait 30 set -o pipefail && xcodebuild -project ToDoListAppTravis.xcodeproj -scheme ToDoListAppTravis -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test | xcpretty --reporter junit --output test_output.xml
